version: "3.3"

services:
    bot:
        build: .
        command: bash -c "python main.py"
        depends_on:
            - mongo_db
        links:
        - mongo_db

    mongo_db:
        image: mongo:latest
