services:
  app_base:
    image: cerrrbot_app
    build:
      context: ../
      dockerfile: "${DOCKERFILE_PATH}"
    volumes:
      - "${APP_CONTAINER_VOLUME_DATA_DIR_PATH}:${DATA_DIR_PATH}"
      - "cerrrbot-data:${CERRRBOT_TG_API_SERVER_WORK_DIR}"
    networks:
      - cerrrbot-network
    env_file:
      - "${ENV_FILE}"

volumes:
  cerrrbot-data:
    external: true

networks:
  cerrrbot-network:
    external: true
    driver: bridge
