version: '3.9'

services:
  app_base:
    image: cerrrbot_app
    build:
      context: ../
      dockerfile: "${DOCKERFILE_PATH}"
    volumes:
      - "${APP_CONTAINER_VOLUME_DATA_DIR_PATH}:${DATA_DIR_PATH}"
    networks:
      - "${CERRRBOT_NETWORK_NAME}"
    env_file:
      - "${ENV_FILE}"

networks:
  cerrrbot_app_network:
    external: true
    driver: bridge