version: '3.9'

services:
  redis:
    image: redis:alpine
    container_name: "${CERRRBOT_REDIS_CONTAINER_NAME}"
    networks:
      cerrrbot-network:
        aliases:
          - "${CERRRBOT_REDIS_HOST}"
    command: --port "${CERRRBOT_REDIS_PORT}"
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "${CERRRBOT_REDIS_PORT}", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
  mongo:
    image: mongo:4.4.18
    container_name: "${CERRRBOT_MONGO_CONTAINER_NAME}"
    volumes:
      - "${CERRRBOT_MONGO_CONTAINER_VOLUME_DATA_DIR_PATH}:/data/db/"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:${CERRRBOT_MONGO_PORT}/test --quiet
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    command: mongod --port "${CERRRBOT_MONGO_PORT}"
    networks:
      cerrrbot-network:
        aliases:
          - "${CERRRBOT_MONGO_HOST}"

networks:
  cerrrbot-network:
    external: true
    driver: bridge
