services:
  redis:
    image: redis:8.0-alpine
    container_name: "${CERRRBOT_REDIS_CONTAINER_NAME}"
    networks:
      cerrrbot-network:
        aliases:
          - "${CERRRBOT_REDIS_HOST}"
    command: --port "${CERRRBOT_REDIS_PORT}"
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "${CERRRBOT_REDIS_PORT}", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
  mongo:
    image: mongo:4.4.18
    container_name: "${CERRRBOT_MONGO_CONTAINER_NAME}"
    ports:
      - "27017:27017"
    volumes:
      - "${CERRRBOT_MONGO_CONTAINER_VOLUME_DATA_DIR_PATH}:/data/db/"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:${CERRRBOT_MONGO_DB_PORT}/test --quiet
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    command: mongod --port "${CERRRBOT_MONGO_DB_PORT}"
    logging:
      driver: "json-file"
      options:
        max-size: "1G"
        max-file: "3"
    networks:
      cerrrbot-network:
        aliases:
          - "${CERRRBOT_MONGO_DB_HOST}"
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    container_name: "${CERRRBOT_TG_API_SERVER_CONTAINER_NAME}"
    ports:
      - "8081:8081"
    environment:
      TELEGRAM_API_ID: "${CERRRBOT_TG_API_ID}"
      TELEGRAM_API_HASH: "${CERRRBOT_TG_API_HASH}"
      TELEGRAM_LOCAL: "true"
      TELEGRAM_VERBOSITY: 3
      TELEGRAM_WORK_DIR: "${CERRRBOT_TG_API_SERVER_WORK_DIR}"
    entrypoint: [ 'sh', '-c', 'chmod -R g+w "$$TELEGRAM_WORK_DIR" && /docker-entrypoint.sh' ]
    volumes:
      - cerrrbot-data:${CERRRBOT_TG_API_SERVER_WORK_DIR}
    networks:
      cerrrbot-network:
        aliases:
          - "${CERRRBOT_TG_API_SERVER_HOST}"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  cerrrbot-data:
    name: cerrrbot-data
    external: true
  cerrrbot-mongo-data:
    name: cerrrbot-mongo-data

networks:
  cerrrbot-network:
    external: true
    driver: bridge
