from settings import (
    REDIS_NOTIFICATIONS_CACHE_KEY_PREFIX,
    REDIS_DEFAULT_CACHE_KEY_PREFIX_NOTIFICATION,
    REDIS_DEFAULT_CACHE_DB_IDX,
    REDIS_NOTIFICATIONS_DB_IDX,
    DEFAULT_CHECK_FOR_DEPRECATED_MESSAGES_TIMEOUT,
    DEFAULT_CHECK_FOR_NEW_MESSAGES_TIMEOUT,
    DEFAULT_CHECK_FOR_NOTIFICATIONS_TIMEOUT
)

CHECK_FOR_NEW_MESSAGES_TIMEOUT = DEFAULT_CHECK_FOR_NEW_MESSAGES_TIMEOUT
CHECK_FOR_DEPRECATED_MESSAGES_TIMEOUT = DEFAULT_CHECK_FOR_DEPRECATED_MESSAGES_TIMEOUT

CACHE_DB_IDX = REDIS_DEFAULT_CACHE_DB_IDX
CACHE_KEY_PREFIX = REDIS_DEFAULT_CACHE_KEY_PREFIX_NOTIFICATION

NOTIFICATIONS_DB_IDX = REDIS_NOTIFICATIONS_DB_IDX

CHECK_FOR_NOTIFICATIONS = DEFAULT_CHECK_FOR_NOTIFICATIONS_TIMEOUT
CACHE_KEY_PREFIX_NOTIFICATION = REDIS_NOTIFICATIONS_CACHE_KEY_PREFIX

CUSTOM_MESSAGE_MIN_ORDER: int = 100
